apiVersion: v1
kind: Pod
metadata:
  name: hello-web-app
spec:
  containers:
    - name: hello-web-app
      image: hello_web_app:latest
      ports:
        - containerPort: 8080
      imagePullPolicy: IfNotPresent  
